<?php
namespace Phossa\Logger\Formatter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-26 at 12:39:54.
 */
class AnsiFormatterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AnsiFormatter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AnsiFormatter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Logger\Formatter\AnsiFormatter::setSlave
     * @todo   Implement testSetSlave().
     */
    public function testSetSlave()
    {
        $slave = new DefaultFormatter(['format' => '%message%']);
        $this->object->setSlave($slave);

        $log = new \Phossa\Logger\LogEntry(
            \Phossa\Logger\LogLevel::INFO,
            'test test'
        );

        $msg = call_user_func($this->object, $log);
        $this->assertEquals('test test', $msg);

    }

    /**
     * @covers Phossa\Logger\Formatter\AnsiFormatter::__invoke
     */
    public function testInvoke()
    {
        $log = new \Phossa\Logger\LogEntry(
            \Phossa\Logger\LogLevel::WARNING,
            'test test'
        );

        $msg = call_user_func($this->object, $log);
        $this->assertContains('.WARNING: test test', $msg);
    }
}
