<?php
namespace Phossa\Logger\Formatter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-29 at 06:12:49.
 */
class DefaultFormatterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DefaultFormatter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DefaultFormatter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Logger\Formatter\DefaultFormatter::__invoke
     */
    public function testInvoke()
    {
        $log = new \Phossa\Logger\LogEntry(
            \Phossa\Logger\LogLevel::INFO,
            'test test'
        );

        $msg = call_user_func($this->object, $log);
        $this->assertContains('[INFO]: test test', $msg);
    }
}
