<?php
namespace Phossa\Logger\Decorator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-29 at 06:12:50.
 */
class InterpolateDecoratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var InterpolateDecorator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InterpolateDecorator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Logger\Decorator\InterpolateDecorator::__invoke
     */
    public function testInvokeScalar()
    {
        $log = new \Phossa\Logger\LogEntry(
            \Phossa\Logger\LogLevel::INFO,
            '{test} {bingo}',
            array('bingo' => '{bingo2}')
        );
        $log2 = call_user_func($this->object, $log);
        $this->assertEquals('{test} {bingo2}', $log2->getMessage());

        $log2->setContext('bingo2', 2);
        $log3 = call_user_func($this->object, $log2);
        $this->assertEquals('{test} 2', $log3->getMessage());

        $log3->setContext('test', true);
        $log4 = call_user_func($this->object, $log3);
        $this->assertEquals('1 2', $log4->getMessage());
    }

    /**
     * @covers Phossa\Logger\Decorator\InterpolateDecorator::__invoke
     */
    public function testInvokeObject()
    {
        $log = new \Phossa\Logger\LogEntry(
            \Phossa\Logger\LogLevel::INFO,
            '{test} {bingo}',
            array('bingo' => $this)
        );

        $log2 = call_user_func($this->object, $log);
        $this->assertEquals(
            '{test} OBJECT: Phossa\Logger\Decorator\InterpolateDecoratorTest',
            $log2->getMessage()
        );

        $log2->setContext('test', new \Exception('test'));
        $log3 = call_user_func($this->object, $log2);
        $this->assertEquals(
            'EXCEPTION: test OBJECT: Phossa\Logger\Decorator\InterpolateDecoratorTest',
            $log3->getMessage()
        );
    }
}
