<?php
namespace Phossa\Logger;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-29 at 06:12:48.
 */
class LogEntryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LogEntry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LogEntry(LogLevel::ERROR, 'test error');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Logger\LogEntry::setMessage
     */
    public function testSetMessage()
    {
        $this->object->setMessage('wow');
        $this->assertEquals('wow', $this->object->getMessage());
    }

    /**
     * @covers Phossa\Logger\LogEntry::getMessage
     */
    public function testGetMessage()
    {
        $this->assertEquals('test error', $this->object->getMessage());
    }

    /**
     * @covers Phossa\Logger\LogEntry::setLevel
     */
    public function testSetLevel()
    {
        $this->object->setLevel(LogLevel::WARNING);
        $this->assertEquals(LogLevel::WARNING, $this->object->getLevel());
    }

    /**
     * @covers Phossa\Logger\LogEntry::getLevel
     */
    public function testGetLevel()
    {
        $this->assertEquals(LogLevel::ERROR, $this->object->getLevel());
    }

    /**
     * @covers Phossa\Logger\LogEntry::setTimestamp
     */
    public function testSetTimestamp()
    {
        $this->object->setTimestamp(10);
        $this->assertEquals(10, $this->object->getTimestamp());
    }

    /**
     * @covers Phossa\Logger\LogEntry::setContexts
     */
    public function testSetContexts()
    {
        $con = [
            'bingo' => 'bingo',
            'wow'   => 'wow'
        ];
        $this->object->setContexts($con);
        $this->assertEquals($con, $this->object->getContexts());
    }

    /**
     * @covers Phossa\Logger\LogEntry::getContexts
     */
    public function testGetContexts()
    {
        $this->assertEquals([], $this->object->getContexts());
    }

    /**
     * @covers Phossa\Logger\LogEntry::setContext
     */
    public function testSetContext()
    {
        $this->object->setContext('wow', 'wow2');
        $this->assertEquals('wow2', $this->object->getContext('wow'));
        $this->assertEquals(null, $this->object->getContext('notfind'));
    }

    /**
     * @covers Phossa\Logger\LogEntry::__toString
     */
    public function testToString()
    {
        $line = (string) $this->object;
        $this->assertContains('test error', $line);
    }
}
