<?php
namespace Phossa\Logger;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-29 at 06:12:52.
 */
class LoggerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Logger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Logger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Logger\Logger::setHandlers
     * @todo   Implement testSetHandlers().
     */
    public function testSetHandlers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Logger\Logger::getHandlers
     * @todo   Implement testGetHandlers().
     */
    public function testGetHandlers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Logger\Logger::setDecorators
     * @todo   Implement testSetDecorators().
     */
    public function testSetDecorators()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Logger\Logger::getDecorators
     * @todo   Implement testGetDecorators().
     */
    public function testGetDecorators()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Logger\Logger::log
     * @todo   Implement testLog().
     */
    public function testLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
