<?php
namespace Phossa\Logger;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-29 at 06:12:50.
 */
class LogLevelTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Logger\LogLevel::getLevelCode
     */
    public function testGetLevelCode1()
    {
        $this->assertEquals(10, LogLevel::getLevelCode(Loglevel::DEBUG));
        $this->assertEquals(20, LogLevel::getLevelCode(Loglevel::INFO));
        $this->assertEquals(30, LogLevel::getLevelCode(Loglevel::NOTICE));
        $this->assertEquals(40, LogLevel::getLevelCode(Loglevel::WARNING));
        $this->assertEquals(50, LogLevel::getLevelCode(Loglevel::ERROR));
        $this->assertEquals(60, LogLevel::getLevelCode(Loglevel::CRITICAL));
        $this->assertEquals(70, LogLevel::getLevelCode(Loglevel::ALERT));
        $this->assertEquals(80, LogLevel::getLevelCode(Loglevel::EMERGENCY));
    }

    /**
     * @covers Phossa\Logger\LogLevel::getLevelCode
     * @expectedExceptionCode Phossa\Logger\Message\Message::INVALID_LOG_LEVEL
     * @expectedException Phossa\Logger\Exception\InvalidArgumentException
     */
    public function testGetLevelCode2()
    {
        $this->assertEquals(0, LogLevel::getLevelCode('', true));
    }
}
