<?php
namespace Phossa\Logger\Handler;

use Phossa\Logger\LogLevel;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-26 at 13:04:43.
 */
class BrowserHandlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BrowserHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BrowserHandler(
            LogLevel::NOTICE,
            [ 'debug' => true ]
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Logger\Handler\BrowserHandler::__invoke
     */
    public function testInvoke()
    {
        $log = new \Phossa\Logger\LogEntry(
            \Phossa\Logger\LogLevel::WARNING,
            'warning warning'
        );
        call_user_func($this->object, $log);
        $class = get_class($this->object);

        $this->expectOutputRegex('#^<script>.+WARNING: warning warning.+</script>$#s');
        $class::flush();
    }
}
