<?php
namespace Phossa\Logger\Handler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-26 at 13:05:25.
 */
class EchoHandlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var EchoHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EchoHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Logger\Handler\EchoHandler::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
